version: '3'
services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - '1935:1935'
    container_name: nginx-rtmp
  camera-broadcast:
    build: camera-broadcast/
    container_name: camera-broadcast
  angular-app:
    build: angular-app/
    ports:
      - '8080:80'
    container_name: angular-app
