version: '3'
services:
  streaming-server:
    container_name: streaming-server
    build: streaming-server/
    ports:
      - '1935:1935'
      - '81:8080'
  #angular-app:
  #  container_name: angular-app
  #  build: angular-app/
  #  ports:
  #    - '8080:80'
