version: '3'
services:
  streamer:
    container_name: streamer
    image: "tiangolo/nginx-rtmp"
    ports:
      - '1935:1935'
  #angular-app:
  #  container_name: angular-app
  #  build: angular-app/
  #  ports:
  #    - '8080:80'
