version: '3'
services:
  streaming-server:
    container_name: streaming-server
    image: "datarhei/nginx-rtmp:1.13.5-dev-armhf"
    ports:
      - '1935:1935'
  #angular-app:
  #  container_name: angular-app
  #  build: angular-app/
  #  ports:
  #    - '8080:80'
